apiVersion: apps/v1
kind: Deployment
metadata:
  name:tam_deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tammy
  template:
    metadata:
      labels:
        app: tammy
    spec:
      containers:
      - name: tam
        image: 390403884347.dkr.ecr.us-east-1.amazonaws.com/tam
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tammy
    k8s-app: tammy
  name: tammy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: tammy
